server:
  port: 8080 # 监听端口
  servlet:
    session:
      timeout: 30m # session 超时时间
spring:
  # 默认的静态资源路径 "classpath:/META-INF/resources/", "classpath:/resources/", "classpath:/static/", "classpath:/public/"
  resources:
    static-locations: classpath:/public/
  mvc:
    favicon:
      enabled: false
    # 静态资源的映射路径，默认是 /**
    static-path-pattern: /public/**
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
  # Thymeleaf 将缓存模板以避免重复解析 XML 源文件,禁用 Thymeleaf 缓存
  thymeleaf:
    cache: false
  # 如果使用 freemarker，禁用缓存
  freemarker:
    cache: false
  # 如果使用 groovy，禁用缓存
  groovy:
    template:
      cache: false
  datasource:
    url: jdbc:mysql://192.168.1.199/yycx_marge?useSSL=true&amp;useUnicode=true&amp&characterEncoding=utf-8&amp;allowMultiQueries=true&amp;zeroDateTimeBehavior=convertToNull&amp;serverTimezone=GMT%2b8
    username: root
    password: yycx!Mysql123
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 10
    minIdle: 10
    maxActive: 20
    maxWait: 60
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x' FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat
  redis:
    host: 127.0.0.1
    port: 6379
    password: foobared
  data:
    mongodb:
      host: 192.168.30.12
      port: 26016
      username: mongodba
      password: mongo!@#
      database: xkx
  devtools:
    restart:
      # devtools 排除不需要检测的资源和增加额外需要监测的资源
      exclude: application.yml
      additional-paths: src/main/webapp
      # 是否重启，如果设置为false禁用，依旧会初始化重启类加载器，但它不会监控文件变化
      enabled: true
      # 触发器文件，只有在修改该文件的时候，才能触发工程重启
      #trigger-file: trigger-file
    livereload:
      # 内嵌的 LiveReload 服务器，可以在资源改变时，触发浏览器更新，禁用设置为false
      # 插件地址 https://chrome.google.com/webstore/detail/livereload/jnihajbhpnppcggbcgedagnkighmdlei
      enabled: true
mybatis:
  typeAliasesPackage: com.example.entity
  mapperLocations: classpath:com/example/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
    call-setters-on-nulls: true
pagehelper:
  offset-as-page-num: true
  row-bounds-with-count: true
  reasonable: true
# springBoot 默认的日志信息会写在控制台，不会写入日志文件，需要设置 path（spring.log）或 file（自定义文件路径 /var/log/my.log）
logging:
  path: D:\var\log
  level:
    root: info
    org.springframework.web: info
